### ISSUE TITLE
library jacinda-lib

### ISSUE THREAD

**Issue by juhp** [vmchale/jacinda#1]
It is not a big thing but I just wanted to check if it is necessary to name the jacinda Haskell library `jacinda-lib` instead of just `jacinda` in jacinda.cabal?

(For context it kind of breaks my measly packaging tool (cabal-rpm): obviously that could be fixed but...)

**Comment by vmchale** [comment]
It's an internal library! That way nothing is exposed on Hackage but I can still use it in the test suite.

Idk if I could add a library but for the time being cabal objects:

```
cabal-3.6.2.0: Illegal internal library name jacinda. Internal libraries
cannot have the same name as the package. Maybe you wanted a non-internal
library? If so, rewrite the section stanza from 'library: 'jacinda' to
'library'.
```

**Comment by juhp** [comment]
Okay no worries - that makes good sense.

**Comment by juhp** [comment]
(Not sure if I mentioned btw, I made a Fedora package available a while ago:
https://copr.fedorainfracloud.org/coprs/petersen/jacinda/)
